# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Eric Ditter.com
name: Eric Ditter.com
email: editter@domain.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

email: ericditter@outlook.com
twitter: eric_ditter
github:  editter
linkedin: ericditter
gravatar_hash: 97595ed7be25efd191e6eca2c96b3e05
disqus_shortname: ericditter

# Build settings
markdown: kramdown
# theme: jekyll-theme-slate
gems:
  - jekyll-feed
  - jekyll-paginate
  # - github-pages
exclude:
  - Gemfile
  - Gemfile.lock

# https://github.com/thinker3197/ink/blob/master/_config.yml
paginate:           5
paginate_path:      "/page:num/"

permalink:          /:year/:month/:day/:title/

nav:
  - name: "About"
    href: "/about"
  - name: "Pet Feeder"
    href: "/pet-feeder-info"

sass:
  style: :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"